### ISSUE TITLE
Review app manager's app categories

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#112]
Currently the app manager contains notions of _pre-installed_, _installed_ and _runnable_ apps.

We should review this and maybe redesign at some point.

**Comment by stonier** [comment]
Going to forget about some notions from the old app manager here and work out what we need...

Q) Initial Rapp Lists: we need them to _seed_ the robot app library but where do they come from?
1. Local
2. Repository (meta-rapp repo)

There could be overlap. Some listed as being available locally, could also be in the repo. Distinguishing point - there may be rapps locally that can't be found in a repo (think closed source business solution). Rapps found in a repo on the other hand, can always be downloaded so they 'become' local.

Dare we say local = installed? No, the local list may be incorrectly given and not actually installed. Or, a repo rapp gets downloaded and is thus gets 'installed'. status, which blurs the definition. Keep local and repo list definitions separately classified.

Q) We filter these lists, how?
1. Verify local apps are installed
2. Platform Info
3. Capability requirements

Q) When to filter?

We do at program startup. Best time since we don't want to list 'maybe runnable' apps in a vague way at a later point.

Q) How to manage runtime lists?
1. Filtered list of Installed rapps currently classified as runnable
2. Filtered list of all 'not yet installed' rapps classified as runnable

Q) How to introspect?
1. Filtering - we only need to introspect the result of the initial filtering step. 
   - Latched publisher of all filtered apps and reason?
2. Runnables - just a plain list of what is actually 'runnable'.
   - Latched publisher on current `list_apps` topic.

**Comment by stonier** [comment]
@bit-pirate your thoughts?

**Comment by bit-pirate** [comment]
> Dare we say local = installed? No, the local list may be incorrectly given and not actually installed. Or, a repo rapp gets downloaded and is thus gets 'installed'. status, which blurs the definition. Keep local and repo list definitions separately classified.

We could drop our rapp lists and use catkin's/package.xml's export feature and implement a discovery method based on that. With this approach we could say _local = installed_. Capability interfaces and providers use this approach.

> Q) When to filter?
> 
> We do at program startup. Best time since we don't want to list 'maybe runnable' apps in a vague way at a later point.

So, on-the-fly/runtime installation of apps won't be support (yet)?

> Q) How to manage runtime lists?
> 
> Filtered list of Installed rapps currently classified as runnable
> Filtered list of all 'not yet installed' rapps classified as runnable

So, the app manager takes care of downloading and installing runnable, but uninstalled apps?

> Q) How to introspect?
> 
> Filtering - we only need to introspect the result of the initial filtering step.
> Latched publisher of all filtered apps and reason?

Good! Allows easy introspections.

> Runnables - just a plain list of what is actually 'runnable'.
> Latched publisher on current list_apps topic.

Would prefer `list_runnable_apps`, but `list_apps` is fine to keep backwards compatibility and avoid the changes otherwise needed.

**Comment by stonier** [comment]
1) :+1: to using package exports, whitelists and blacklists

2) on-the-fly installation is fine, can enable that with debs very quickly. The filtering should be done at startup, i.e. create an index of possible rapps discovered via local package exports, and repo url's. After that installation is just a matter of looking up this filtered index for installation details.

3) Yes, app manager takes care of downloading and installing runnable, but uninstalled apps. And updating those two list variables as it does so.

4) yeah, would prefer a name change, but will work with the current handle for now.

**Comment by stonier** [comment]
Closing this, work to do in #120, #121, #122.

**Comment by bit-pirate** [comment]
What are the new categories?

**Comment by stonier** [comment]
For now, just a single list of runnable apps. I'm not going to maintain any other lists, except what is sitting on a latched publisher `/app_manager/incompatible_app_list`.

In future, the `list_app` topic should expand to something like:
- `installed_apps[]`
- `available_apps[]`
- `running_apps[]`

but I'm not going to plot out something specific for this till we reinsert installation code.
