### ISSUE TITLE
Rapp Module

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_app_platform#139]
Need a rapp version of rospack script which indexes(or caches) all rapps in ROS_PACKAGE_PATH, introspects, and resolves full specification of nested rapps.

**Comment by stonier** [comment]
This needs to be a module since it will be used by various users. 

Initial goal:

> Create an index that can help the app manager list apps for the concert using parent spec names, interfaces and parameters. 

Initial requirement spec for this module (no work about the app manager here - lets use a separate issue for that):
- _rocon_app_utilities_: a new package for supporting classes/functions
- Creation of an index of rapps from the package path.
  - This should probably be like a dictionary of rapps, indexed by rapp resource name strings
  - Jack's scheduler requests has a good example of setting up a custom 'dict'.
  - A method for returning a sub-index of 'implemented' rapps only (i.e. those that have launchers).
  - A method for returning a sub-index of 'implemented' and 'rocon uri' compatible rapps
  - i.e. arg of this function should be a rocon uri
- Upon creation of the index, rapps should follow their parent specs and fill out overloadable and public spec variables.
  - This should be automatically done when creating the index (i.e. after parsing the package path, but before returning the index to the user). 
- Python nosetests for these features

Questions:
- Should start/stop app functionality be in the rapp class api?
  - I am thinking no, but undecided. Would be yes if there were other users other than app manager wanting start/stop functionality. If not, then keep that code in the app manager.

Later: 
- In initial index creation, pruning (with error message) of rapp chains which have _cyclic parent specs_.
- Work out if we want to have a corresponding msg class (i.e. toMsg etc).

**Comment by jihoonl** [comment]
- Jack's scheduler requests has a good example of setting up a custom 'dict'.

Link please
- Should start/stop app functionality be in the rapp class api?
  - I am thinking no, but undecided. Would be yes if there were other users other than app manager wanting start/stop functionality. If not, then keep that code in the app manager.

I like the idea of making rapp independent from app manager and provide command tool like `rapp start <rapp_name>` which allows easy way of starting and testing rapps. However, it could become another wrapper for roslaunch as well.

**Comment by jihoonl** [comment]
Started document here.

https://github.com/robotics-in-concert/rocon_app_platform/tree/rapp_module/rocon_app_utilities

**Comment by jihoonl** [comment]
Rapp module should be factored out from rocon_app_manager and have an independent package. To avoid cross dependency between rapp manager and rapp utility. 

This kind of dependency tree may be better.

https://docs.google.com/a/yujinrobot.com/drawings/d/1Con2-9SgKET2OosXAGVCSYkkx-Tu1AMTQ2NlomWzIMw/edit

**Comment by jihoonl** [comment]
Redmine updates about rapp spec.

http://redmine.robotconcert.org/projects/opp/wiki/Rocon_Apps

**Comment by stonier** [comment]
What's the difference between rocon_app and rocon_app_utilities? I was imagining rocon_app_utilities as the rocon_app module. Can't see a reason for both rocon_app and rocon_app_utilities.

**Comment by jihoonl** [comment]
I was thinking of making rapp module more independent from rapp_manager to prevent cross importing between rocon_app_utilities and rocon_app_manager package. rocon_app_manager will use rocon_app_utilities in the future meanwhile rocon_app_utilities needs some nice functions in rocon_app_manager/rapp.py.  Also cross-referencing is bad software design. 
So I wanted to I wanted to factor out rapp class from rocon_app_manager.

and I thought it would be funny that 'utility' package contains core module.

**Comment by jihoonl** [comment]
Some information on redmine is updated. Question. 

I think `paired_clients` is optionally inheritable and `required_capability` is overridable.  What's your opinion?

http://redmine.robotconcert.org/projects/opp/wiki/Rocon_Apps

**Comment by stonier** [comment]
Yeah, I can see `rocon_app_manager/rapp.py` almost disappearing. But worry about that later, indexer first, app manager second, possible command line tools and caching third, app repositories fourth. One bite at a time.

|  I thought it would be funny that 'utility' package contains core module.

Yeah, I only suggested utilities for lack of anything better. An indexer isn't really core though...it is a kind of utility. Anyway, rocon_app is strange - sounds like it is a rapp (aka our rocon_apps). If you have another idea, throw it out there, but this name isn't really important as people aren't likely to use it directly. Focus on code and tests. 

> I think `paired_clients` is optionally inheritable and

Yeah, you might have a correct hunch about this. Example teleop. It might have a generic teleop android app in the ancestor `rocon_apps/teleop`. But `turtlebot/teleop` might want it's own branded teleop android app.  What about considering `paired_clients` as non-inheritable and non-overridable?

`required_capability` should be like the launcher. It's a specific part of the implementation. i.e. non-inheritable and non-overridable.

**Comment by stonier** [comment]
Those two tables you made make things much clearer. Looking at them I realised the inheritable and overridable definitions are redundant. Going to the top most parent for `public_interface` and `public_parameters` is actually the same as the nearest since only a top most parent may have those variables.

So I deleted the second table (the variable) and superscripted the fields on the first table which inherit from their parents if none are present.

Also some other minor tweaks:
- `N` for `required_capability` in the virtual rapp (it's an implementation thing).
- Made `paired_clients` an optional thing for implementations only.
- `N` for `public_parameters` and `public_interface` in children. They absolutely aren't allowed to change their top parent's spec. This is the interface that makes them a conforming child.

Looks good!

**Comment by jihoonl** [comment]
indexer api

http://192.168.10.129/rocondoc/rocon_app_utilities/html/indexer.html

**Comment by jihoonl** [comment]
Redmine specs has been ported to rst.

https://github.com/robotics-in-concert/rocon_app_platform/blob/rapp_module/rocon_app_utilities/doc/rapp.rst

**Comment by jihoonl** [comment]
https://github.com/robotics-in-concert/rocon_app_platform/commit/0352576861a0a269ffb87595b05cfe40ff2e44b2#diff-575c178e63d10d0eb73ca65424903e6eR76

parent_specification and public_interface are mutually exclusive?

**Comment by stonier** [comment]
> parent_specification and public_interface are mutually exclusive?

Yes. Children should absolutely never override public_interface/public_parameters.

**Comment by jihoonl** [comment]
The old rapp implementation used to allow not to have public_interface. Is this still true?
Or should we force all rapps to have required fields?

**Comment by stonier** [comment]
Certainly, even for the ancestor, empty public_interface and public_parameters is permissable. Exact use case requirement: `rocon_apps/chirp`.

**Comment by jihoonl** [comment]
With that means, public_interface and public_parameters are optional.

**Comment by stonier** [comment]
Yes.

**Comment by jihoonl** [comment]
How about display and description? do they need to be `required`?

**Comment by stonier** [comment]
I would prefer to force the user to fill these out in ancestor rapps otherwise everyone will be lazy and introspecting will be messy or useless.

**Comment by jihoonl** [comment]
Rapp v2 with `rocon_app_utilities` has been merged and working well.
