### ISSUE TITLE
factor out capability from rapp_manager and put them into rapp

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_app_platform#143]
Capability is internal feature of rapp. It should not do anything with rapp manager.

**Comment by bit-pirate** [comment]
Cant follow you. The rapp manager needs some minimal capability management, i.e. communicating with the capability server and tracking the status of the caps. What exactly do you want to factor out?

**Comment by stonier** [comment]
It very much is part of the rapp manager as 
1. there is currently no generic way of specifying capability dependencies inside a launcher
2. the rapp manager uses the capability specification to determine whether the rapp is runnable before running it.

1) can be solved in a roundabout way by having a node that handles the capability part by inserting that node with the appropriate parameters into the rapp's launcher, but since it's constant behaviour, there's a good argument for including that in the app manager instead of having to include it in every single rapp launcher. The rapp's public_interface specification is an example of exactly the same situation (we could have a node which is 'launched' that does this job instead of the app manager too).

The second point is important though. Think of it as a mechanism that supports the rocon uri check with more attention to fine details.
