### ISSUE TITLE
rename interface in .rapp to public_interface

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_app_platform#144]

**Comment by bit-pirate** [comment]
Please point out the files/folder needing to be updated.

**Comment by stonier** [comment]
I think this is coming from the conversation we had in #137 where I referred to `public_interface` and we had some discussion on that. Looks like I am mistaken in thinking that was labelled `public_interface` as the .rapp files themselves currently just refer to it as the `interface` (e.g. [chirp.rapp](https://github.com/robotics-in-concert/rocon_app_platform/blob/hydro-devel/rocon_apps/apps/chirp/chirp.rapp).

Given that it is already this way, I'm happy to leave it as it stands. I prefer `public_interface` but it's not a sufficient enough preference to go changing what we're already using/used to. If you want to, speak up and then scratch the itch otherwise let's close this one.

**Comment by jihoonl** [comment]
`public_parameters` becomes `parameter` as well?

**Comment by stonier** [comment]
What the hell, since we're changing things anyway, let's move to `public_interface` and `public_parameters`.

**Comment by jihoonl** [comment]
resolved by pullrequests.
