### ISSUE TITLE
Make use of slots in RappManager

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#164]
As we started to do this in newer python packages, we should start making use of **slots** in the RappManager class as well.

**Comment by stonier** [comment]
Not critical.

Main purpose of using the slots was not for the real reason to use slots, but to identify to the dev what are the variables of the class. This is a problem in python since it lets you define them anywhere, even mid-function and this makes it easy to be sloppy about what parameters are currently valid and used.

I now do this by pushing for some conventions:
1. Use `cvar` and `ivar` sphinx docstrings in the class documentation.
2. Instantiate every variable use use in the `__init__` even if you are just setting it to None.
