### ISSUE TITLE
Rapp uninstaller

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#197]
We need to implement this feature. So let's discuss how this could be achieved (@stonier, @esteve).

**Comment by stonier** [comment]
Do we? Are we talking about uninstalling rapps or all their dependencies? Is there actually a use case for uninstalling apart from some nice concept of _completeness_?

**Comment by stonier** [comment]
@esteve don't worry about this one unless you have a particular idea I didn't think of - we need to find a way to explain that we're leveraging a shared software ecosystem and not doing android style install/uninstallable apps and that changes the ball game. So...we'll handle this internally.

**Comment by dirk-thomas** [comment]
Just some further thought about it...

A rapp is basically "installed" when all its dependencies are available. There is currently no additional "installed" flag stored somewhere.

But since multiple rapps can have the same dependencies the "installed" attribute must be modeled separately in order to "install" / "uninstall" these rapps individually.

Also when it comes down to uninstalling the dependencies (which are Debian packages) it becomes very problematic which are safe to be uninstalled and which should stay on the system.
