### ISSUE TITLE
How to handle resource names in rapps

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_app_platform#204]
Over the past couple of days, discussions on how to setup a remote repository with cached index has raised some subtle issues over the current rapp specification policies. 

**Current Status**

A rapp begins and ends with a rapp file that is exported in the `package.xml`, e.g.

```
  <export>
    <rocon_app>apps/talker/talker.rapp</rocon_app>
  </export>
```

This file contains some configuration but is also a pointer to other files that help provide the specification for the rapp. Currently this consists of:
- _Launch_ : a launcher for the rapp.
- _Public Interface_ : a yaml file that exposes the rapp's public interface
- _Icon_ : usually a .png or .jpg file

Depending on the kind of rapp, none, some or all of these files must be present. The problem we have though, is that these files are always referred to via a [ros resource name](http://wiki.ros.org/ROS/Concepts#Names.Package_Resource_Names), e.g. for `talker.rapp`

```
display: Talker
description: Default ros style talker tutorial
compatibility: rocon:/
launch: rocon_apps/talker.launch
public_interface: rocon_apps/talker.interface
icon: rocon_bubble_icons/conductor.png
```

**Are Resource Names a Killer?**

I mentioned in the hangout today with @dirk-thomas that resource names for icons were a killer for a remote user of rapps (e.g. a web ide that wants to introspect rapps) that doesn't have a ros environment. This however doesn't have to be true. Consider:
- The rapp indexer runs over this directory while _inside_ a ros environment itself
  - This means the indexer can find these files, regardless of where they are.
- The indexer fetches all these files (or the contents thereof in the case of yamls) and dumps these into the index

In other words ros resource names disappear in the dumping process. So...we can do this, but there is still the question of things like - how do you execute a launcher from a tarballed index?

**Resource Names are still Complicated Though**

This is still awfully complicated though. I'm rather inclined to simplify the whole process by eliminating sharability of files:
- A rapp consists of a folder that is exported in the manifest like this:

```
  <export>
    <rocon_app>apps/talker</rocon_app>
  </export>
```
- A .rapp file _must_ exist inside this folder - this contains the complete specification of the rapp.
- Public interface file and icon, if present must be in this folder.
- The main .rapp file just refers to them by filename
  - Or the rapp indexer just assumes to find these files by extension, thus removing the need for them to be listed in the .rapp file itself.

**Comment by stonier** [comment]
@dirk-thomas @bit-pirate thoughts?

I created a dummy  [rocon_apps](https://github.com/robotics-in-concert/rocon_apps) repo, and will fill it in tomorrow with some fake rapps that we can use for testing some ideas. You might like to fork [rocon_app_platform](https://github.com/robotics-in-concert/rocon_app_platform), delete the rocon_apps package there, and start building the libraries and tools there in earnest while testing them on this new fake [rocon_apps](https://github.com/robotics-in-concert/rocon_apps) repo.

**Comment by dirk-thomas** [comment]
I think we have two different kind of resources:
- some need to be accessible when querying and presenting a list of available rapps (e.g. the icon)
- some are only necessary when the rapp is actually being invoked (e.g. the launch file)

For the second kind it makes sense to reference them by resource name since they should ultimately come from the ROS package.

For the first kind we might just use a relative path (relative to the .rapp file I would suggest). In general the files should be siblings but any kind of hierarchy should be fine since it ends up in the index anyway.

Based on past experience I would definitely recommend to use explicit references rather then implicit assumptions where to find the files.

If the developer decides that the launch file should be part of the rapp a relative path would be fine for that too. We should just make sure that the type of reference is unambiguous. E.g. `foo/bar.launch` is not since it could be either a launch file bar.launch in _package_ `foo` or in a _subfolder_ `foo`.

**Comment by stonier** [comment]
Ok, all of the above sounds reasonable. Only real question is how to deal with that ambiguity. Can't really change the 'ros resource name' style as its used everywhere. Could enforce relative names to start with a `./` but that'd be inconvenient. Would prioritising the lookup with a fallback if it fails work? 

Need to make some decisions so we can define what the indexer has to do and make any immediately urgent updates right now.

**Decisions**
- All locations must be referenced _relative_ to the `.rapp` file with the exception of the roslaunch file.
- Support local relative _and_ ros resource lookups for the **roslaunch** file.
  - pkg part must be part of catkin_depends for the package
- Handle the ambiguity for roslaunch file lookup by priority
  - the indexer probably doesn't care, deal with it when invoking it (i.e. in app manager)
  - if name is not a ros resource name format -> relative lookup
  - if name is a ros resource name format -> relative lookup
  - if relative lookup fails -> fall back to ros resource lookup

As dirk comments below, this avoids an unwanted ros resource blocking a relative file

**Benefits**
- The indexer does not need to go hunting down extra files to put in the index.
- Development and Release Rapp Repos look the same

**Necessary Actions**
- Create a dummy rapps repo conforming to the above decisions
- Local indexing needs to be updated for this policy

@bit-pirate does this work for you?

**Comment by dirk-thomas** [comment]
The "problem" with this order is that a file `foo/bar.launch` can not be used as a relative file because it is potentially overlayed by a package `foo`. That package could appear even long after the rapp was created.

Therefore I would suggest changing the resolve order to:
- try to resolve resource with a relative lookup
- if that relative resource does not exist and the value is a valid ros resource name try to resolve it that way

**Comment by stonier** [comment]
Good point. Have to get tuned to thinking about every possible which way things can break like you guys do :stuck_out_tongue_winking_eye: 

I updated the notes above. Setting up a rapp repo now.

**Comment by stonier** [comment]
Rapp repo is at https://github.com/robotics-in-concert/rocon_rapps. @dirk-thomas  feel free to test, mutate and evolve that as you wish. 
Closing this issue here - I think we're resolved.

**Comment by stonier** [comment]
Note that rocon_rapps is currently not runnable with the app manager but should be sufficient for testing the rocon app list, index(?), install etc. commands until both the local app indexer and app manager are both working for non-resource names everywhere.
