### ISSUE TITLE
Why I am getting notifications from this project?

### ISSUE THREAD

**Issue by steida** [robotics-in-concert/rocon_app_platform#208]

**Comment by stonier** [comment]
You are not a member of the organization. I don't know of any other reason you'd get notifications apart from something in your own private preferences.

**Comment by steida** [comment]
So I have to ask github. Probably some error on their side. Thank you for quick response.

**Comment by bit-pirate** [comment]
Maybe you are watching it? Also, on the right, there is a subscribe button. Does it say you are subscribed?

**Comment by stonier** [comment]
1. The user steida != este, hence this issue was a misdirection that couldn't solve the problem.
2. Este was accidentally added instead of esteve
   - When you add a team member, github is trying really hard to autocomplete but this is sometimes slower than your typing...so in this case it autocompleted with este even when you fully typed esteve quickly followed by enter.

**Comment by steida** [comment]
I have account este too. Remove me please.

**Comment by stonier** [comment]
This has already been done 2 or 3 days ago, the problem is elsewhere.

**Comment by stonier** [comment]
You can see for yourself if you are in the organisation anywhere at

https://github.com/orgs/robotics-in-concert/members
