### ISSUE TITLE
[rocon_app_utilities] dependency checker missinterprets installable apps

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#210]
Installable apps are wrongly added to the list of installed apps, if at least one dependency is available. 

https://github.com/esteve/rocon_app_platform/blob/remote_index/rocon_app_utilities/src/rocon_app_utilities/dependencies.py#L70-L84

**Comment by dirk-thomas** [comment]
As far as I can see the existing API works different fro what you expect.

For each rapp all run dependencies are getting classified into "installable", "not installable", "already installed".

The existence of a rapp `foo` in the third dictionary does not mean that it is _completely_ installed. It only means that these dependencies are installed. If the same rapp is also part of the first or second dictionary then some dependencies are still missing.

While this might look very confusing (also to me) that is the way the API was designed before PR 196.

A more intuitive API would return a single dict mapping rapp names to tuples. And for each rapp a tuple of three lists contains the installable, not installable and already installed packages. But since we aim to keep the existing API I did not change the semantic.

**Comment by bit-pirate** [comment]
I agree the current API is confusing. And BTW, "keeping the API" was only meant to target the code, which was there before we started working on the new indexer and installer.

Now, looking at a new, more intuitive API, I would suggest to keep the three existing categories - installed, uninstalled, noninstallable - with the only difference being, that a rapp only exists in one list. That is, a  rapp is considered _installed_, if all its dependencies are already installed, _installable_, if one or more of its dependencies are missing, and _noninstallable_, if one or more of its dependencies are unknown/not available. The later two categories should also contain the not installed/not available dependencies.

In my use case I would like to directly tell from the method's returned data, if a given app (precisely speaking its dependencies) is installed, installable or noninstallable without the need of parsing the returned information another time (see https://github.com/robotics-in-concert/rocon_app_platform/blob/auto_rapp_installation/rocon_app_manager/src/rocon_app_manager/rapp_manager.py#L284-L287). Also, in the later two case, I'd like to known, which are the missing packages. This info would enable the user to install/start looking for the missing pieces.

**Comment by dirk-thomas** [comment]
Imo it would be a bad API if it returns three tuples and a rapp is always only part of one. Why?

Because the API can simply not return the necessary information to print simple debug information about the state of a rapp, like this:

```
The rapp "foo" is [installable | not installable | already installed] because:
- the following dependencies are available but not yet installed: ...
- the following dependencies are neither available nor installable: ...
- the following dependencies are already installed: ...
```

I would propose to return a single dict mapping from rapp names to X where X must contain all dependencies (classified by their state) and also allow the easy queries you want to answer `isInstalled()`. Therefore X should be a class contains the three members for the different dependencies (currently the tuples) and also provide functions to answer your queries.

**Comment by bit-pirate** [comment]
> Because the API can simply not return the necessary information to print simple debug information about the state of a rapp

Sorry for my ignorance. Could you explain why this is not possible? The method contains all required information already.

> I would propose to return a single dict mapping from rapp names to X where X must contain all dependencies (classified by their state) and also allow the easy queries you want to answer isInstalled(). Therefore X should be a class contains the three members for the different dependencies (currently the tuples) and also provide functions to answer your queries.

Sounds good as well, but also more complicated.

**Comment by dirk-thomas** [comment]
The current API returns the following values:

```
(
    {'rapp1':
        ['installable_dependency_A', ...],
    },
    {'rapp1':
        ['not_installable_dependency_B', ...],
    },
    {'rapp1':
        ['already_installed_dependency_C', ...],
    },
)
```

The API provides all information about the rapp but the structure makes it "difficult" to decide the status of `rapp1`. In this example it is actually `not installable` since one of the dependencies is not installable.

The problem with your proposal (let each rapp only appear in one of the tuples) is that the API is hiding information, therefore it is not possible for not installable rapps to list the already installed dependencies or the installable dependencies anymore: 

```
(
    {},
    {'rapp1':
        (
            ['installable_dependency_A', ...],
            ['not_installable_dependency_B', ...],
            ['already_installed_dependency_C', ...],
        )
    },
    {},
)
```

Imo only with more code the same complete information can be exposed while still allowing simple access:

```
{'rapp1':
    RappDependencyObject()
}
```

where each `RappDependencyObject` has the following API:

```
installable_dependencies = []
not_installable_dependencies = []
already_installed_dependencies = []
are_all_dependencies_already_installed(): bool
are_all_missing_dependencies_installable() : bool
are_any_dependencies_not_installable() : bool
```

**Comment by bit-pirate** [comment]
Since this thread got a bit lengthy, @dirk-thomas and I quickly sync'ed by chat.

Conclusion:

The approach of using nested tuples, such as 

```
(
    {},
    {'rapp1':
        (
            ['installable_dependency_A', ...],
            ['not_installable_dependency_B', ...],
            ['already_installed_dependency_C', ...],
        )
    },
    {},
)
```

Would not hide any information, but is not easy to comprehend.

Hence we decided to implement the proposed `RappDepdendencyObject`, because the benefits of a more easy to use and comprehensible API outweighs the drawback of a more complex implementation.
