### ISSUE TITLE
Auto-detect support automatic rapp installation 

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#212]
Better than setting a parameter in the app manager's roslauncher would be an automatic detection of whether or not everything has been set up to support automatic installation of apps.

Our current method is enabling password-less installation using apt-get via sudoers (see #211 for more details).

One method of detecting, if this has been set-up, is actually trying to install a know to be available package (sth standard). However, if in the same shell the user has provided the sudo password before - let's say for the manual installation of a package - the app manager could falsely detect automatic app installation has been enabled.

Need to put some thinking in this to enable a robust detection of this.

**Comment by stonier** [comment]
1) Just launch a command in a python subprocess with a fresh shell, that should work.

2) Don't even worry about it, just proceed to try every time the user asks to start a rapp, and if it works, great, if it doesn't, pop out a warning of decent immensity and obviality to the user.

I prefer 2).

**Comment by stonier** [comment]
2) is bad. The concert then cannot be sure if such a resource is allocatable before starting it.

So yeah, we have to validate at startup, i.e. detect whether the user can run sudo with apt-get or rosdep or similar.

I don't think we have to go as far as detecting if the user has got temporary sudo access though. It is a minor use case and because it is human interactive, we can always throw them a noisy warning later when an automatic install fails.

**Comment by stonier** [comment]
Not going to support this in its current incarnation. We'll pick it up again and probably slightly differently in future incarnations.
