### ISSUE TITLE
[app utilities] Abolish one-child-policy

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#230]
It looks one can only inherit from a virtual or child rapp, but not an ancestor rapp.

```
[WARN] [WallTime: 1399346647.154206] App Manager : 'rocon_apps/teleop' is invalid [Ancestor has already been taken by other rapp]
```

Is there a reason for this limitation?

In my use case, I would like to have complete `rocon_apps/teleop` rapp and then inherit from that. Am I doing sth wrong here @stonier @jihoonl ?

**Comment by bit-pirate** [comment]
Wait, I think I misunderstood the limitation here: It's not the problem of interiting from an ancestor, but only one rapp can inherit from a specific rapp at a time. Is that understanding correct? If yes, why is it like that?

**Comment by stonier** [comment]
Because [Highlander](http://en.wikipedia.org/wiki/Highlander_%28film%29) is an awesome cult movie (there can be only one!).

His rapp indexer was crawling the package path and throwing up problems if it found multiple implementations because the rapp manager of course, can only run one of these. As you've pointed out though, this is very brittle and the rapp manager needs some hints as in #187

**Comment by bit-pirate** [comment]
Roger. I remember that old issue again. Changed the issue title to avoid confusion.

**Comment by jihoonl** [comment]
Could #187 address this issue?

**Comment by stonier** [comment]
Yes, merge any relevant information here into that.

**Comment by jihoonl** [comment]
done by #248
